### ISSUE TITLE
electron中使用报错 Error: The specified procedure could not be found

### ISSUE THREAD

**Issue by as13579e** [hyj1991/v8-profiler-next#59]
复现项目：electron-quick-start
electron版本：12.0.6

已经通过electron-rebuild重新构建v8-profiler-next，,在项目中require("v8-profiler-next")，然后npm start启动项目，会报错
App threw an error during load
Error: The specified procedure could not be found.
\\?\C:\web\electron-quick-start\node_modules\v8-profiler-next\build\binding\Release\electron-v12.0-win32-x64\profiler.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\web\electron-quick-start\node_modules\v8-profiler-next\lib\binding.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

**Comment by hyj1991** [comment]
`win` 下的这个问题比较复杂，大多是 build 的 addon 版本和当前的 win 环境不适配或者编译的 addon 不完整导致的，你可以自己尝试下 stackoverflow 下解决方式

**Comment by as13579e** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hyj1991** [comment]
没有更多跟进先关闭了

**Comment by LiZhuMyCase** [comment]
我有同样的问题。electron 版本是 26.6 win32 x64. 可以解决一下吗？谢谢

**Comment by as13579e** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
